### ISSUE TITLE
permanent Plex token

### ISSUE THREAD

**Issue by CFenner** [glitch452/MMM-PlexNowPlaying#11]
In the [Plex docs](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/) it's mentioned that the xToken is only temporary. How long is it valid? Do I need to update it regularly or is this done by the module? How can I obtain a permanent token?

**Comment by glitch452** [comment]
Hi, I believe the token is tied to the device sign-in that was used to generate it.  As far as I know it doesn't expire.  It should work until the device is de-authorized (At least I haven't had any issues with mine expiring since I created this module.  You can see the device access in Plex from the `Authorized Devices` page in the settings.  As far as I know there is no way to generate ate a more permanent token.  It would be possible to update the module to sign in with your Plex credentials, but I felt that approach was a bit too invasive and a security risk, especially since that level of access is not required to access the server's API for basic data like this.

**Comment by TATUMTOT** [comment]
I use this to create custom tokens for everything.
https://gist.github.com/fleXible/709e4583086b926646cb5304361693b4

**Comment by CFenner** [comment]
Thanks, then I stick to this token.
